spring.application.name=EventosFaltantes

spring.datasource.url=jdbc:postgresql://dpg-d7ijs73bc2fs73dufajg-a.virginia-postgres.render.com:5432/eventos_7b1m?sslmode=require
spring.datasource.username=eventos_7b1m_user
spring.datasource.password=XbXbYsDEKGujR4HA8HEkrM3u1pjUU2Km
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${PORT:8080}

hibernate.dialect=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=update

